permalink: /:year/:month/:day/:title.html

paginate: 2

title: "jdost.github.io"
author: "jdost"
tagline: "writing about stuff"
url: http://jdost.github.io

exclude: ["Makefile", "README.md", "github.conf", "s/less"]
pygments: true

disqus:
   enabled: true
   account: jdost
analytics:
   enabled: true
   account: UA-37975007-1
