permalink: /:year/:month/:day/:title.html
auto: true

paginate: 2

title: "jdost.github.com"
author: "jdost"
tagline: "writing about stuff"
url: http://jdost.github.com

exclude: ["Makefile", "README.md", "s/less"]
pygments: true

disqus:
   enabled: true
   account: jdost
analytics:
   enabled: false
   account: UA-37975007-1
